# Generated by Django 4.2.16 on 2024-09-25 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotaMatch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Match')),
                ('adding_date', models.DateField(default=datetime.datetime.now, verbose_name='Adding date')),
            ],
        ),
        migrations.CreateModel(
            name='DotaUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Profile')),
                ('name', models.CharField(max_length=50, verbose_name='Player name')),
                ('status', models.BooleanField(default=True, verbose_name='User status')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(default=datetime.datetime.now, verbose_name='Date of Scan')),
                ('parsed_before', models.BooleanField(verbose_name='Was match parsed before')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opendota_forcer.dotamatch', verbose_name='Match')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opendota_forcer.dotauser', verbose_name='Profile')),
            ],
        ),
    ]
