# Generated by Django 4.2.2 on 2024-09-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opendota_forcer', '0002_dotaprofile_alter_scan_profile_id_delete_dotauser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='match_id',
            new_name='match_instance',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='profile_id',
            new_name='profile_instance',
        ),
    ]
